USE College_DB; 
CREATE TABLE Person (
  CampusWideID INT NOT NULL UNIQUE AUTO_INCREMENT,
  FirstName VARCHAR(20) DEFAULT NULL,
  LastName VARCHAR(20) DEFAULT NULL,
  MiddleName VARCHAR(20) DEFAULT NULL,
  MaidenName VARCHAR(20) DEFAULT NULL,
  SocialSecurity INT DEFAULT NULL,
  DoB VARCHAR(8) NOT NULL,
  BannerID VARCHAR(20) DEFAULT NULL,
  Gender VARCHAR(20) DEFAULT NULL,
  Sex VARCHAR(10) DEFAULT NULL,
  Race VARCHAR(25) DEFAULT NULL,
  Role VARCHAR(20) NOT NULL ,
  HomeAddress VARCHAR(70) DEFAULT NULL,
  SecondaryAddress VARCHAR(70) DEFAULT NULL,
  PrimaryPhone VARCHAR(14) DEFAULT NULL,
  SecondaryPhone VARCHAR(14) DEFAULT NULL,
 
  
  PRIMARY KEY (CampusWideID)
) 
